<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FlashcardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Define the list of flashcards you want to insert
        $flashcards = [
            [
                'list_id' => 1,
                'palabra' => 'run',
                'traduccion' => 'correr',
                'cat_gramatical' => 'verbo',
                'pronunciacion' => 'rʌn',
                'frase_ejemplo' => 'I can run a mile in five minutes.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 1,
                'palabra' => 'table',
                'traduccion' => 'mesa',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => 'ˈteɪ.bəl',
                'frase_ejemplo' => 'He lived in a room with only two chairs, a bed and a table.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 1,
                'palabra' => 'always',
                'traduccion' => 'siempre',
                'cat_gramatical' => 'adverbio',
                'pronunciacion' => 'ˈɔːl.weɪz',
                'frase_ejemplo' => 'It\'s always cold in this room.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 1,
                'palabra' => 'buy',
                'traduccion' => 'comprar',
                'cat_gramatical' => 'verbo',
                'pronunciacion' => 'baɪ',
                'frase_ejemplo' => 'Eventually she had saved enough money to buy a small car.',
                'notas' => 'bought | bought',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'list_id' => 2,
                'palabra' => 'cut corners',
                'traduccion' => 'recortar',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'When building contractors try to cut corners on foundations, it is disastrous.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'a blessing in disguise',
                'traduccion' => 'no hay mal que por bien no venga; ser una suerte en el fondo',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'Not being chosen to play that role turned out to be a blessing in disguise.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'a dime a dozen',
                'traduccion' => 'a montones, a patadas, hasta debajo de las piedras',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'In Hollywood, aspiring young actresses are a dime a dozen.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'hit the sack',
                'traduccion' => 'irse al sobre, irse a dormir',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'I\'ve got to get up early tomorrow, so I\'m going to hit the sack.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'break a leg',
                'traduccion' => '¡mucha suerte!',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'As he left the dressing room his fellow actors shouted "Break a leg!"',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'easy does it',
                'traduccion' => 'vísteme despacio que tengo prisa',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => '"Can I put it down now?" "Yes, but it\'s fragile so easy does it."',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'beat around the bush',
                'traduccion' => 'andarse con rodeos, irse por las ramas',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'Stop beating around the bush and give me the real reason!',
                'notas' => 'UK English also: beat about the bush',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'better late than never',
                'traduccion' => 'más tarde que nunca',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => '"Sorry I was late for the meeting today; I got stuck in traffic." "That\'s okay; better late than never."',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'bite the bullet',
                'traduccion' => 'hacer de tripas corazón, tragar con lo que venga',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'You will just have to bite the bullet; there\'s no other option.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'call it a day',
                'traduccion' => 'dar por terminado, dar por finalizado',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'I\'ve been working for hours, I\'m gonna call it a day.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 2,
                'palabra' => 'cut someone some slack',
                'traduccion' => 'dejárselo pasar a alguien, hacer excepciones con alguien, no ser tan duro con alguien',
                'cat_gramatical' => 'frase idiomática',
                'pronunciacion' => '',
                'frase_ejemplo' => 'I\'ll have to cut my new employee some slack; this is all new to her.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 3,
                'palabra' => 'chien',
                'traduccion' => 'perro',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => '',
                'frase_ejemplo' => 'Ceux qui disent que le chien est le meilleur ami de l\'homme ont raison.',
                'notas' => 'femenino: chienne',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 3,
                'palabra' => 'vache',
                'traduccion' => 'vaca',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => '',
                'frase_ejemplo' => 'La vache est un animal sacré en Inde, la tuer est un sacrilège.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 3,
                'palabra' => 'lapin',
                'traduccion' => 'conejo',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => '',
                'frase_ejemplo' => 'Il a un lapin à poil long comme animal de compagnie.',
                'notas' => 'femenino: lapine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 3,
                'palabra' => 'cheval',
                'traduccion' => 'caballo',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => '',
                'frase_ejemplo' => 'Mon cheval est un véritable pur-sang.',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 3,
                'palabra' => 'chat',
                'traduccion' => 'gato',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => '',
                'frase_ejemplo' => 'On dit qu\'un chat retombe toujours sur ses pattes.',
                'notas' => 'femenino: chatte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '吃',
                'traduccion' => 'comer',
                'cat_gramatical' => 'verbo',
                'pronunciacion' => 'chī',
                'frase_ejemplo' => '我爱吃宫保鸡丁。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '总是',
                'traduccion' => 'siempre',
                'cat_gramatical' => 'adverbio',
                'pronunciacion' => 'zǒngshì',
                'frase_ejemplo' => '她总是晚饭后出来散步。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '狗',
                'traduccion' => 'perro',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => 'gǒu',
                'frase_ejemplo' => '我讨厌养狗的人。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '家',
                'traduccion' => 'casa; familia',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => 'jiā ',
                'frase_ejemplo' => '他一放假就回家。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '书',
                'traduccion' => 'libro',
                'cat_gramatical' => 'verbo',
                'pronunciacion' => 'shū ',
                'frase_ejemplo' => '她爱看书。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '散步',
                'traduccion' => 'pasear',
                'cat_gramatical' => 'verbo',
                'pronunciacion' => 'sànbù',
                'frase_ejemplo' => '我们去公园散步了。',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'list_id' => 4,
                'palabra' => '猫',
                'traduccion' => 'gato',
                'cat_gramatical' => 'sustantivo',
                'pronunciacion' => 'māo',
                'frase_ejemplo' => '有趣的是猫和狗对人内心的了解要比其他人更多。难道不是吗？',
                'notas' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all the flashcards at once
        DB::table('flashcards')->insert($flashcards);
    }
}
